version: '3.8'

services:
  app:
    image: service-transaction
    container_name: service-transaction
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=transaction
      - DB_PORT=3306
      - DB_HOST=localhost
      - PORT=27017
  